//
//  DetailModels.swift
//  PokedexMitch
//
//  Created by Mitchell Samaniego on 07/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases

    enum PokemonDetail {
        struct Request {
            let id: Int
        }

        struct Response {
            var detail: PokemonDetailModel?
            var error: Error?
        }

        struct ViewModel {
            var detail: PokemonDetailModel?
            var error: String?
        }
    }
}
