//
//  DetailWorker.swift
//  PokedexMitch
//
//  Created by Mitchell Samaniego on 07/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailInterface {
    func fetchDetailOfPokemon(request: Detail.PokemonDetail.Request, completion: @escaping (Result<PokemonDetailModel, Error>) -> Void)
}

class DetailWorker: DetailInterface {
    func fetchDetailOfPokemon(request: Detail.PokemonDetail.Request, completion: @escaping (Result<PokemonDetailModel, Error>) -> Void) {
        NetworkManagerService.shared.getDetailOfPokemon(of: request.id) { result in
            switch result {
            case let .success(response):
                completion(.success(response))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }
}
