//
//  DetailPresenter.swift
//  PokedexMitch
//
//  Created by Mitchell Samaniego on 07/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationInterface {
    func presentDetailOfPokemon(response: Detail.PokemonDetail.Response)
}

class DetailPresenter: DetailPresentationInterface {
    weak var viewController: DetailDisplayInterface?

    // MARK: Do something

    func presentDetailOfPokemon(response: Detail.PokemonDetail.Response) {
        let viewModel = Detail.PokemonDetail.ViewModel(detail: response.detail, error: response.error?.localizedDescription)
        viewController?.displayPokemonDetail(viewModel: viewModel)
    }
}
