//
//  PrincipalViewModels.swift
//  PokedexMitch
//
//  Created by Mitchell Samaniego on 07/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PrincipalViewModels {
    // MARK: Use cases

    enum FetchPokemonList {
        struct Request {
            let count: Int
        }

        struct Response {
            var pokemonList: PokemonList?
            var error: Error?
        }

        struct ViewModel {
            var pokemonList: [PokemonModel]?
            var isHaveNext: Bool?
            var errorMessage: String?
        }
    }

    enum FetchFilteredPokemonList {
        struct Request {
            let textToSearch: String
        }

        struct Response {
            var pokemon: PokemonModel?
            var error: Error?
        }

        struct ViewModel {
            var pokemon: PokemonModel?
            var errorMessage: String?
        }
    }

    enum FetchPokemonType {
        struct Request {
            let type: String
        }

        struct Response {
            var pokemons: PokemonsForType?
            var error: Error?
        }

        struct ViewModel {
            var pokemons: [PokemonModel]?
            var errorMessage: String?
        }
    }
}
