//
//  PrincipalViewViewController.swift
//  PokedexMitch
//
//  Created by Mitchell Samaniego on 07/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol PrincipalViewDisplayInterface: AnyObject {
    func displayPokemonList(viewModel: PrincipalViewModels.FetchPokemonList.ViewModel)
    func displayPokemonFiltered(viewModel: PrincipalViewModels.FetchFilteredPokemonList.ViewModel)
    func displayPokemonsForType(viewModel: PrincipalViewModels.FetchPokemonType.ViewModel)
}

class PrincipalViewController: UIViewController {

    // MARK: Properties

    var interactor: PrincipalViewBusinessInterface?
    var router: (NSObjectProtocol & PrincipalViewRoutingInterface & PrincipalViewDataPassing)?

    // MARK: UI
    private let buttonView = UIView()
    private let cleanButton = UIButton()
    private var collectionView: UICollectionView!
    private lazy var searchController = UISearchController()
    private let containerTypesView = UIView()
    private var containerTypesViewHeightContraint: NSLayoutConstraint!
    private let tableViewForTypes = UITableView()

    // Empty View
    private let emptyView = UIView()
    private let emptyImage = UIImageView()
    private let emptyLabel = UILabel()
    
    // Variables
    private let disposeBag = DisposeBag()
    private var pokemonsList: [PokemonModel] = []
    private var filteredPokemons: [PokemonModel] = []
    private var isHaveNext: Bool = true
    private var isSearchActive: Bool = false
    private var isShowTypes: Bool = false

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        manageSearchBarController()
        fetchPokemonList()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = PrincipalViewInteractor()
        let presenter = PrincipalViewPresenter()
        let router = PrincipalViewRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    private func setupView() {
        view.backgroundColor = .black.withAlphaComponent(0.7)
        emptyView.backgroundColor = .black
        setupCollectionAndTable()

        buttonView.registerView(cleanButton)

        let principalStackView = UIStackView(arrangedSubviews: [containerTypesView, buttonView, collectionView])
        principalStackView.axis = .vertical
        principalStackView.distribution = .fill
        principalStackView.spacing = 10
        principalStackView.alignment = .fill

        view.registerView(principalStackView)

        containerTypesView.registerView(tableViewForTypes)
        
        view.registerView(emptyView)
        emptyView.registerView(emptyImage)
        emptyView.registerView(emptyLabel)

        containerTypesViewHeightContraint = containerTypesView.heightAnchor.constraint(equalToConstant: 0)
        containerTypesViewHeightContraint.isActive = true
        
        NSLayoutConstraint.activate([
            principalStackView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            principalStackView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            principalStackView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            principalStackView.bottomAnchor.constraint(equalTo: view.bottomAnchor),

            tableViewForTypes.topAnchor.constraint(equalTo: containerTypesView.topAnchor, constant: 12),
            tableViewForTypes.leadingAnchor.constraint(equalTo: containerTypesView.leadingAnchor, constant: 24),
            tableViewForTypes.trailingAnchor.constraint(equalTo: containerTypesView.trailingAnchor, constant: -24),
            tableViewForTypes.bottomAnchor.constraint(equalTo: containerTypesView.bottomAnchor, constant: -12),

            cleanButton.heightAnchor.constraint(equalToConstant: 30),
            cleanButton.trailingAnchor.constraint(equalTo: buttonView.trailingAnchor, constant: -24),
            cleanButton.topAnchor.constraint(equalTo: buttonView.topAnchor),
            cleanButton.bottomAnchor.constraint(equalTo: buttonView.bottomAnchor),
            
            emptyView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            emptyView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            emptyView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            emptyView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            
            emptyImage.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            emptyImage.bottomAnchor.constraint(equalTo: emptyLabel.topAnchor, constant: -12),
            emptyImage.heightAnchor.constraint(equalToConstant: 120),
            emptyImage.widthAnchor.constraint(equalToConstant: 150),
            
            emptyLabel.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            emptyLabel.leadingAnchor.constraint(equalTo: emptyView.leadingAnchor, constant: 24),
            emptyLabel.trailingAnchor.constraint(equalTo: emptyView.trailingAnchor, constant: -24)
        ])
        
        emptyImage.image = UIImage(named: "emptyImage")
        emptyLabel.attributedText = .init(string: "Parece que no hemos podido encontrar resultados. Intenta con otra busqueda", attributes: NSAttributedString.pokemonDetailNumber)
        emptyLabel.numberOfLines = 0
        emptyLabel.textAlignment = .center
        emptyView.isHidden = true

        // Set Button To Clean
        buttonView.isHidden = true
        cleanButton.addTarget(self, action: #selector(cleanSearchOrFiltered), for: .touchUpInside)
        cleanButton.setAttributedTitle(.init(string: "Limpiar", attributes: NSAttributedString.pokemonDetailNumber), for: .normal)

        // Set Button To Search For Type
        let barButton = UIBarButtonItem(title: "Buscar por Tipo", style: .done, target: self, action: #selector(searchForType))
        navigationItem.rightBarButtonItem = barButton
    }

    // Set Components

    private func setupCollectionAndTable() {
        let flowLayout = UICollectionViewFlowLayout()
        flowLayout.scrollDirection = .vertical
        collectionView = UICollectionView(frame: .zero, collectionViewLayout: flowLayout)
        collectionView.delegate = self
        collectionView.dataSource = self
        collectionView.register(PokemonCell.self, forCellWithReuseIdentifier: PokemonCell.identifier)
        collectionView.backgroundColor = .clear

        tableViewForTypes.separatorStyle = .none
        tableViewForTypes.delegate = self
        tableViewForTypes.dataSource = self
        tableViewForTypes.backgroundColor = .clear
    }

    private func manageSearchBarController() {
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.barStyle = .black
        searchController.searchBar.delegate = self
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.hidesNavigationBarDuringPresentation = false
        searchController.searchBar.searchBarStyle = .minimal
        searchController.searchBar.sizeToFit()
        searchController.searchBar.isTranslucent = true

        navigationController?.navigationBar.isTranslucent = true

        // Add searchController to navigation bar
        navigationItem.searchController = searchController
        searchController.searchBar.placeholder = "Buscar un pokemon por nombre o ID"
    }

    // MARK: Do Something

    private func fetchPokemonList() {
        let request = PrincipalViewModels.FetchPokemonList.Request(count: pokemonsList.count)
        interactor?.fetchPokemons(request: request)
    }

    private func fetchListFiltered(with text: String) {
        let request = PrincipalViewModels.FetchFilteredPokemonList.Request(textToSearch: text)
        interactor?.fetchFilteredPokemons(request: request)
    }

    private func fetchPokemonsForType(_ type: String) {
        let request = PrincipalViewModels.FetchPokemonType.Request(type: type)
        interactor?.fetchPokemonsOfType(request: request)
    }

    // Helpers

    @objc private func cleanSearchOrFiltered() {
        isSearchActive = false
        searchController.searchBar.isHidden = false
        navigationItem.rightBarButtonItem?.isHidden = false
        filteredPokemons.removeAll()
        collectionView.reloadData()
        collectionView.scrollToItem(at: IndexPath(row: 0, section: 0), at: .top, animated: true)
        buttonView.isHidden = true
    }

    @objc private func searchForType() {
        if !isSearchActive {
            isShowTypes.toggle()
        } else {
            isShowTypes = false
        }
        
        searchController.searchBar.isHidden = isShowTypes
        UIView.animate(withDuration: 1) {
            self.containerTypesViewHeightContraint.constant = self.isShowTypes ? 200 : 0
            self.view.layoutIfNeeded()
        }
    }

    private func reloadCollectionView() {
        DispatchQueue.main.async {
            self.collectionView.reloadData()
        }
    }
}

extension PrincipalViewController: PrincipalViewDisplayInterface {
    func displayPokemonList(viewModel: PrincipalViewModels.FetchPokemonList.ViewModel) {
        if let list = viewModel.pokemonList, let isHaveNext = viewModel.isHaveNext {
            pokemonsList.append(contentsOf: list)
            self.isHaveNext = isHaveNext
            emptyView.isHidden = true
            reloadCollectionView()
        }

        if let error = viewModel.errorMessage {
            print(error)
            emptyView.isHidden = false
        }
    }

    func displayPokemonFiltered(viewModel: PrincipalViewModels.FetchFilteredPokemonList.ViewModel) {
        if let pokemon = viewModel.pokemon {
            filteredPokemons.append(pokemon)
            reloadCollectionView()
            emptyView.isHidden = true
        }

        if let error = viewModel.errorMessage {
            emptyView.isHidden = false
            print(error)
        }
    }

    func displayPokemonsForType(viewModel: PrincipalViewModels.FetchPokemonType.ViewModel) {
        if let pokemons = viewModel.pokemons {
            filteredPokemons.append(contentsOf: pokemons)
            reloadCollectionView()
            collectionView.scrollToItem(at: IndexPath(row: 0, section: 0), at: .top, animated: true)
            buttonView.isHidden = false
            emptyView.isHidden = true
        }

        if let error = viewModel.errorMessage {
            emptyView.isHidden = false
            print(error)
        }
    }
}

extension PrincipalViewController: UISearchControllerDelegate, UISearchBarDelegate {
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        isSearchActive = true
        guard let text = searchBar.text else { return }
        filteredPokemons.removeAll()
        fetchListFiltered(with: text.lowercased())
    }

    func searchBarCancelButtonClicked(_ searchBar: UISearchBar) {
        isSearchActive = false
        filteredPokemons.removeAll()
        collectionView.reloadData()
        emptyView.isHidden = true
    }
}

extension PrincipalViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        TypeCells.allCases.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.attributedText = .init(string: TypeCells(rawValue: indexPath.row)?.typeString.capitalized ?? "", attributes: NSAttributedString.pokemonDetailNumber)
        cell.preservesSuperviewLayoutMargins = false
        cell.selectionStyle = .none
        cell.layoutMargins = UIEdgeInsets(top: 0, left: 24, bottom: 0, right: 0)

        return cell
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        isSearchActive = true
        searchForType()
        searchController.searchBar.isHidden = true
        filteredPokemons.removeAll()
        fetchPokemonsForType("\(indexPath.row + 1)")
    }
}

extension PrincipalViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let id = (isSearchActive ? filteredPokemons[indexPath.row].id : indexPath.row + 1) ?? 1
        router?.navigateToDetailView(pokemonID: id)
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        isSearchActive ? filteredPokemons.count : pokemonsList.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: PokemonCell.identifier, for: indexPath) as! PokemonCell
        let id = (isSearchActive ? filteredPokemons[indexPath.row].id : indexPath.row + 1) ?? 1
        cell.setInfo(with: isSearchActive ? filteredPokemons[indexPath.row] : pokemonsList[indexPath.row], id)
        return cell
    }

    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        if indexPath.row == (isSearchActive ? filteredPokemons.count : pokemonsList.count) - 4,
            isHaveNext {
            fetchPokemonList()
        }
    }

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let width = collectionView.bounds.width / 2 - 10
        return CGSize(width: width, height: 210)
    }
}

extension PrincipalViewController: DetailDisplayDelegate {
    func fetchWithType(_ type: String) {
        isSearchActive = true
        navigationItem.rightBarButtonItem?.isHidden = true
        filteredPokemons.removeAll()
        searchForType()
        searchController.searchBar.isHidden = true
        fetchPokemonsForType(type)
    }
}
